### ISSUE TITLE
Converting an AsyncAPI JSON document returns YAML

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/converter-js#91]
#### Describe the bug
When you provide the following AsyncAPI in JSON format:
```json
{
    "asyncapi": "2.2.0",
    "info": {
        "title": "Rust processor",
        "version": "0.2.0"
    },
    "defaultContentType": "json",
    "channels": {
        "test": {
            "publish": {
                "message": {
                    "payload": true
                }
            }
        }
    }
}
```

It returns the following when running `asyncapi-converter test.json > test2.json`
```yaml
asyncapi: 2.3.0
info:
  title: Rust processor
  version: 0.2.0
defaultContentType: json
channels:
  test:
    publish:
      message:
        payload: true
```

#### Expected behavior
Expected it to return JSON.
