### ISSUE TITLE
Show how to incorporate the library into workflows

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/converter-js#92]
#### Reason/Context
It would be nice to show how to use the library in different workflows.

For example, how to incorporate it into a GH action workflow. 

```yaml
name: Convert the AsyncAPI document
env:
  GH_USER: jonaslagoni
  GH_EMAIL: <jonas-lt@live.dk>
on:
  workflow_dispatch: 
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install converter
        run: npm i -g @asyncapi/converter 
      - name: Convert AsyncAPI file
        run: asyncapi-converter ./asyncapi.json > ./asyncapi.json
      - name: Create Pull Request with updated document
        uses: peter-evans/create-pull-request@v3
        with:
          token: '${{ secrets.GH_TOKEN }}'
          commit-message: 'feat: convert to newest AsyncAPI version'
          committer: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          author: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          title: 'feat: convert to newest AsyncAPI version'
          body: Update to newest AsyncAPI version
          branch: 'convert/asyncapi_file'
```
